enum Hierarchys {
    Civil = 'CIVIL',
    Alumno = 'ALUMNO',
    Bombero = 'BOMBERO',
    Distinguido = 'DISTINGUIDO',
    CaboSegundo = 'CABO SEGUNDO',
    CaboPrimero = 'CABO PRIMERO',
    SargentoSegundo = 'SARGENTO SEGUNDO',
    SargentoPrimero = 'SARGENTO PRIMERO',
    SargentoMayor = 'SARGENTO MAYOR',
    Teniente = 'TENIENTE',
    PrimerTeniente = 'PRIMER TENIENTE',
    Capitan = 'CAPITAN',
    Mayor = 'MAYOR',
    TenienteCoronel = 'TENIENTE CORONEL',
    Coronel = 'CORONEL',
    General = 'GENERAL',
    PrimerGeneral = 'PRIMER GENERAL',
}
