export enum InfrastructureType {
    RecreationalPlaces = 'SITIOS DE REUNIÓN / RECREACIONALES',
    Educational = 'EDUCACIONALES',
    MedicalAssistance = 'MEDICO ASISTENCIAL / ASISTENCIALES',
    Institutional = 'INSTITUCIONALES / OFICIALES',
    Lodging = 'ALOJAMIENTO',
    Residential = 'RESIDENCIALES',
    Commercial = 'COMERCIALES',
    Industrial = 'INDUSTRIALES',
    Warehouse = 'ALMACÉN / ALMACENAJE',
    Parking = 'ESTACIONAMIENTOS / GARAJES',
    Laboratories = 'LABORATORIOS',
    Workshops = 'TALLERES',
    GasStations = 'ESTACIONES DE SERVICIOS',
    Ecclesiastical = 'ECLESIASTICOS',
    Landfills = 'RELLENOS SANITARIOS',
    Club = 'CLUB',
  }