enum InfrastructureType {
    RecreationalPlaces = 'sitios de reunión / recreacionales',
    Educational = 'Educacionales',
    MedicalAssistance = 'medico asistencial / asistenciales',
    Institutional = 'institucionales / oficiales',
    Lodging = 'Alojamiento ',
    Residential = 'Residenciales',
    Commercial = 'Comerciales',
    Industrial = 'Industriales',
    Warehouse = 'Almacén / Almacenaje',
    Parking = 'Estacionamientos / Garajes',
    Laboratories = 'Laboratorios',
    Workshops = 'Talleres',
    GasStations = 'Estaciones de Servicios',
    Ecclesiastical = 'Eclesiásticos',
    Landfills = 'Rellenos Sanitarios',
    Club = 'Club',
}
