export enum OperativeAreas {
    Rescues = 'RESCATES',
    Fire = 'INCENDIO',
    PreHospital = 'PREHOSPITALARIA',
    PLAEDBEM = 'PLAEDBEM',
    Technology = 'TECNOLOGÍA',
    Prevention = 'PREVENCIÓN',
    Education = 'EDUCACIÓN',
    Motorized = 'MOTORIZADOS',
    Logistics = 'LOGÍSTICA',
    Workshop = 'TALLER',
    HumanTalent = 'TALENTO HUMANO',
    Communications = 'COMUNICACIONES',
    Transmissions = 'TRANSMISIONES',
    MATPEL = 'MATPEL',
    Archives = 'ARCHIVOS',
    Press = 'PRENSA',
    Transport = 'TRANSPORTE',
    AirDivition = 'DIVISION AEREA',
    NauticDivition = 'DIVISION NAUTICA',
    Risks = 'RIESGOS',
}