enum UnitTypes {
    Ambulancia = 'AMBULANCIA',
    Moto = 'MOTO',
    MaterialesPeligrosos = 'MATERIALES PELIGROSOS',
    Rescate = 'RESCATE',
    Bicicleta = 'BICICLETA',
    Transporte = 'TRANSPORTE',
    PuestoDeMando = 'PUESTO DE MANDO',
    SuperCisterna = 'SUPER CISTERNA',
    BombaPesado = 'BOMBA (PESADO)',
    BombaLigero = 'BOMBA LIGERO',
    MotobombaLigero = 'MOTOBOMBA LIGERO',
    Buggy = 'BUGGY',
    Cisterna = 'CISTERNA',
    Helicoptero = 'HELICOPTERO',
    MotobombaForestal = 'MOTOBOMBA FORESTAL',
    Motobomba = 'MOTOBOMBA',
    SuplidorDeAire = 'SUPLIDOR DE AIRE',
    Lancha = 'LANCHA',
}
