export const Colors = [
    "Blanco",
    "Negro",
    "Gris Plata",
    "Gris Oscuro",
    "Rojo",
    "Azul",
    "Verde",
    "Amarillo",
    "Naranja",
    "Marrón",
    "Beige",
    "Dorado",
    "Plateado",
    "Bronce",
    "Turquesa",
    "Violeta",
    "Rosa",
    "Magenta",
    "Cian",
    "Ocre",
    "Granate",
    "Ámbar",
    "Coral",
    "Lavanda",
    "Carmesí",
    "Caqui",
    "Chartreuse",
    "Aguamarina",
    "Azul Eléctrico"
];