export const Colors = [
    "BLANCO",
    "NEGRO",
    "GRIS PLATA",
    "GRIS OSCURO",
    "ROJO",
    "AZUL",
    "VERDE",
    "AMARILLO",
    "NARANJA",
    "MARRÓN",
    "BEIGE",
    "DORADO",
    "PLATEADO",
    "BRONCE",
    "TURQUESA",
    "VIOLETA",
    "ROSA",
    "MAGENTA",
    "CIAN",
    "OCRE",
    "GRANATE",
    "ÁMBAR",
    "CORAL",
    "LAVANDA",
    "CARMESÍ",
    "CAQUI",
    "CHARTREUSE",
    "AGUAMARINA",
    "AZUL ELÉCTRICO"
];